[package]
name = "vaults"
version = "0.1.0"
authors = ["Martin Pobaschnig <martin.pobaschnig@protonmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
once_cell = "1.0.2"
quick-error = "2.0.0"
strum = "0.21"
strum_macros = "0.21"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
proc-mounts = "0.2"
adw = { version = "0.1.0-alpha-2", package = "libadwaita" }
gtk = { version = "0.2.0", package = "gtk4", features = ["v4_2"] }
