name: flatpak

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: jochumdev/flatpak-github-actions/flatpak-builder@builder-update-deps
        with:
          bundle: vaults.flatpak
          manifest-path: io.github.mpobaschnig.Vaults.Devel.json
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
